name: dbt_template
profile: dbt_template
version: '1.0.0'
require-dbt-version: ">=1.7.0"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - target
  - dbt_packages

on-run-end:
  - "{{ dbt_artifacts.upload_results(results) }}"

seeds:
  dbt_template:
    +schema: static
    +tags: static_schema

models:
  dbt_template:
    mart:
      +materialized: table
      +schema: mart
      +tags: mart_schema
    staging:
      +materialized: view
      +schema: staging
      +tags: staging_schema

  dbt_artifacts:
    +database: "{{ env_var('SNOWFLAKE_PRODUCTION_DATABASE') }}"
    +schema: dbt_artifacts