name: dbt Daily Job

on:
  workflow_dispatch:
  # schedule:
    # Runs at 5 AM UTC every day
    # - cron: '0 5 * * *'

permissions:
  contents: read

jobs:
  dbt_daily_job:
    runs-on: ubuntu-latest

    # Add concurrency group to prevent parallel runs within the same PR
    # Only keep the latest run, cancel the prior
    # Manifest will not be uploaded by time of cancel, next merge job will run all changes
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true

    env:
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_DBT_USER: ${{ vars.SNOWFLAKE_DBT_USER }}
      SNOWFLAKE_DBT_PASSWORD: ${{ secrets.SNOWFLAKE_DBT_PASSWORD }}
      SNOWFLAKE_PRODUCTION_DATABASE: ${{ vars.SNOWFLAKE_PRODUCTION_DATABASE }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@main

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: dbt debug
      run: dbt debug -t prod

    - name: dbt deps
      run: dbt deps -t prod
    
    - name: dbt build
      run: dbt build -t prod
